### ISSUE TITLE
Will this pipeline check if images are already ome pyramidal?

### ISSUE THREAD

**Issue by NHPatterson** [hubmapconsortium/ome-tiff-pyramid#6]
Vanderbilt TMC's next data release's incoming processed microscopy images are  bioformats' `xmlvalid` (docs [here](https://docs.openmicroscopy.org/bio-formats/6.5.1/users/comlinetools/xml-validation.html)) validated, pyramidal OME-TFF images with much the same settings as outlined in this repository (same `tile-size`, etc.). They also work with [vitessce-image-viewer](https://github.com/hms-dbmi/viv) as I've went back and forth with @ilan-gold.  Is there any reason to run them through to `bioformats2raw` -> `raw2ometiff` pipeline and could a check by performed for necessity? (this can be easily achieved with python's `tifffile` library and the aforementioned `xmlvalid`). If not, not a big deal. 

Thanks,
Heath

**Comment by ilan-gold** [comment]
@NHPatterson We were just going to re-run it for GE.  I don't think it's any extra work and it would probably be more work to index your files directly (since we have never done that before).

Also, your images now appear in the correct spot i.e no "[Image Pyramid]" datasets anymore: https://portal.hubmapconsortium.org/browse/dataset/dc289471333309925e46ceb9bafafaf4

**Comment by NHPatterson** [comment]
Ok thanks for the clarification, also nice to see the [image pyramid] removed.
